name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  offline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bunx supabase start
      - run: bun run verify
